### ISSUE TITLE
elogind support

### ISSUE THREAD

**Issue by krifisk** [linuxmint/cinnamon-session#105]
```
 * cinnamon-session version (cinnamon-session --version)
cinnamon-session 3.6.1

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Gentoo

For our non-systemd users we're using elogind to provide logind, the following crude patch works for cinnamon-session downstream but it would be nice if we could work on getting this upstreamed (note the libsystemd version check on line 45 is not from master, but used to disable automagic, but otherwise it should apply cleanly)

https://gitweb.gentoo.org/repo/gentoo.git/tree/gnome-extra/cinnamon-session/files/cinnamon-session-3.6.1-elogind.patch

**Comment by leigh123linux** [comment]
Don't expect much/any interest in supporting elogind, gentoo will need to submit fully working PR's to add support.

**Comment by Yamakuzure** [comment]
As always I have to say that requesting "fully working PRs" for such a tiny, almost minuscule, patch is an enormous hindrance to get any work done.


- For any Contributor on this project it is just
    1. Download FILE
    2. patch -p 1 < FILE
  and you are done. You do not even have to test widely, because the patch already *is* tested on dozens of user systems. (*)

- For any non-Contributor it means 
    1. Fork
    2. Clone
    3. branch&checkout branch
    4. patch
    5. build & confirm
    6. pull master (and maybe rebase)
    7. merge
    8. push
    9. File PR
    10. Wait ... wait ... ping and wait... 
    11. Read "doesn't apply, please pull and rebase"
    12. Go back to vi.

I have seen this many times already, and the "PR request" means in most cases: "Maybe next year, we have soooo many PRs..."

Maybe it is different with Cinnamon, maybe not. But at the end of the day, someone will have to spend a lot of time to get this done and ends with an unused fork in their account.

...and all of that just because nobody wants to call "patch" just once... (*)

(*) Yes, I know, there is more to it. But still it is next to nothing compared to the extreme incongruity between time/effort and the size of this patch.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/cinnamon-session/commit/4559b1d1fb644e7b0e12abc1d07b6902e0e70ed0
