### ISSUE TITLE
indicator-stickynotes doesn't start on startup

### ISSUE THREAD

**Issue by ericjding** [linuxmint/cinnamon-session#58]
I like to use the program indicator-stickynotes instead of the Sticky Notes desklet. However, Cinnamon won't let me start indicator-stickynotes on startup for some reason; after looking on various forums and poring through source code of a couple different possibilities, I finally narrowed it down to a change in csm-manager.c dating back to mid-2014:

> cinnamon-session (2.2.2) qiana; urgency=medium
>
>  * Make shutdown and failwhale dialogs use CENTER instead of CENTER_ALWAYS, to stop the small jump the dialogs usually make right after they pop up.
>  * Logout/Shutdown dialogs: Capture focus and keyboard input and block until dialog is closed.
>  * session-properties (startup programs): show 0 in the list when there is no startup delay defined, as well as a 0 in the spinner during item edit.
>  * Remove logging from previous commit
>  * Block ubuntu indicator-* services from starting.
>
> -- Clement Lefebvre <root@linuxmint.com>  Fri, 27 Jun 2014 14:33:56 +0100

So cinnamon-session was changed to intentionally block "ubuntu indicator-* services" from starting. But that means that *any* application with a desktop file whose name starts with indicator- is blocked. I don't fully understand what is referred to as an "ubuntu indicator-* service" -- is the effect that this has on indicator-stickynotes intentional, or is it an unintended effect? If it's unintended, is there a better way to do what Cinnamon is doing here without affecting apps like indicator-stickynotes? If it's intentional, why does Cinnamon not allow users to autostart programs like this one (running it manually doesn't seem to do any harm...)?

Cf. http://superuser.com/questions/803825/system-load-and-keylock-indicator-will-not-autostart-in-linux-mint-17, http://forums.linuxmint.com/viewtopic.php?f=47&t=176826

**Comment by mtwebster** [comment]
Cinnamon doesn't really support appindicator apps and many of them interfere with or break Cinnamon's implementations of these functions.  Ubuntu users would install Cinnamon, and have issues because of these programs without understanding why, or how to fix. This is why we prevent them from autostarting.  There are proper methods of preventing a program starting depending upon your desktop environment, but because of historical issues with our *internal* desktop name, they can't really be used in this case.

I've added this commit: https://github.com/linuxmint/cinnamon-session/commit/e4e8a7171aea177e75f0bd0ce64bff6e83f7d096 will allow you to override the built-in list.  If we implement real support for these programs in the future, we'll re-evaluate how all of this is handled, this is just a quick fix for now.

**Comment by ericjding** [comment]
Thanks for the quick response and workaround. So what sort of issues would I be looking for as far as appindicator applications interfering with Cinnamon? I haven't noticed any problems running indicator-stickynotes, but is this just because I'm not paying attention?

**Comment by mtwebster** [comment]
There's nothing wrong with stickynotes, but many other indicator applets duplicate/hijack functionality already provided in Cinnamon, and it can be confusing and non-obvious why this is happening.  There is one (can't remember the specific name) that brings in other dependencies, and will cause gnome-screensaver to be installed and run at startup (along side Cinnamon's screensaver.)

**Comment by clefebvre** [comment]
It's indicator-session, maybe we should blacklist that one in particular.

**Comment by clefebvre** [comment]
Fixed on master.
