### ISSUE TITLE
Qt 5.7 still loads default style

### ISSUE THREAD

**Issue by Arquanite** [linuxmint/cinnamon-session#84]
Every app build with Qt 5.7 using Qt Creator looks really bad (even on Mint 18.1). Why this isn't fixed for this long?
Screenshot with sample app
![zrzut ekranu z 2016-12-11 13-40-03](https://cloud.githubusercontent.com/assets/15730544/21091080/499998c4-c044-11e6-9f12-4d4c2a171fbd.png)

**Comment by Tateyuki-Shigaraki** [comment]
I think cinnamon-session shouldn't unset QT_STYLE_OVERRIDE, so users are allowed to set the style they want. (it is unset [here](https://github.com/linuxmint/cinnamon-session/blob/master/cinnamon-session/main.c#L401))

Currently there is no way to have this variable control the applications launched with cinnamon-sessions, since:
- setting the variable in .profile is too early (will be set in the DM but unset by cinnamon-session)
- setting the variable in .bashrc is too late (only application lanched in a terminal will have the variable)

I think QT_STYLE_OVERRIDE should be modifiable by users, for example to set it to "adwaita" or "adwaita-dark" when [adwaita-qt](https://github.com/MartinBriza/adwaita-qt) is installed.

**Comment by leigh123linux** [comment]
@Tateyuki-Shigaraki post

```
env |grep QT
```

**Comment by Arquanite** [comment]
I thought nobody will ever see this issue

**Comment by Tateyuki-Shigaraki** [comment]
I realize this is old, but anyway:

QT_STYLE_OVERRIDE=adwaita-dark
QT_QPA_PLATFORMTHEME=qt5ct

I set those in my .profile, and I patched cinnamon-session to not unset them back then.

But now I have updated (several times) and it seems to be fixed (I use an unpatched version).
I can't tell exactly when it was fixed because I believe I've done several updates.
I think this can be closed.

**Comment by itzexor** [comment]
Qt theme support is no longer handled here as of #102
